"""add steps_count to water_logs

Revision ID: 0875ad9f64a9
Revises: 53622d9fbc8d
Create Date: 2025-12-26 21:45:42.492758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0875ad9f64a9'
down_revision: Union[str, Sequence[str], None] = '53622d9fbc8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('water_logs', sa.Column('steps_count', sa.Integer(), nullable=True))
    op.alter_column('water_logs', 'amount_ml',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('water_logs', 'amount_ml',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('water_logs', 'steps_count')
    
    # ### end Alembic commands ###
