"""added emotion date in emotion_log

Revision ID: 1de57edd5ce6
Revises: fe1c25d91325
Create Date: 2025-11-10 14:18:28.647865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '1de57edd5ce6'
down_revision: Union[str, Sequence[str], None] = 'fe1c25d91325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emotion_logs', sa.Column('emotion_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emotion_logs', 'emotion_date')
    # ### end Alembic commands ###
