"""updated leave_status enum CANCELLED

Revision ID: 52828bff621c
Revises: d9bb355538fd
Create Date: 2025-11-25 20:04:09.823594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '52828bff621c'
down_revision: Union[str, Sequence[str], None] = 'd9bb355538fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
