"""add: image url column to kb

Revision ID: f6a1d6fc82d0
Revises: 1cbb7317540a
Create Date: 2025-12-01 16:55:06.113217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'f6a1d6fc82d0'
down_revision: Union[str, Sequence[str], None] = '1cbb7317540a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_chunk', sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_chunk', 'image_url')
    # ### end Alembic commands ###
